// Video Plan Controller - handles operations on saved video plans
// These plans are generated by the AI (via the aiController)
// and retrieved through the weddingController

const VideoPlan = require('../models/VideoPlan');

// DELETE /api/video-plans/:id - Delete a single saved video plan
const deleteVideoPlan = async (req, res) => {
  try {
    const { id } = req.params;

    // 1. Validate that the ID is a valid MongoDB ObjectId (24 hex characters)
    if (!id.match(/^[0-9a-fA-F]{24}$/)) {
      return res.status(400).json({
        success: false,
        message: 'Invalid video plan ID',
      });
    }

    // 2. Find the plan and delete it in one step
    // Returns the deleted document, or null if it didn't exist
    const plan = await VideoPlan.findByIdAndDelete(id);

    // 3. If nothing was found, the plan doesn't exist
    if (!plan) {
      return res.status(404).json({
        success: false,
        message: 'Video plan not found',
      });
    }

    // 4. Return a success response
    res.status(200).json({
      success: true,
      message: 'Video plan deleted successfully',
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: error.message,
    });
  }
};

module.exports = {
  deleteVideoPlan,
};